openapi: 3.0.2
info:
  title: Konnect Audit Log Settings
  version: 3.0.3
  description: The API for configuring Kong Konnect Audit Logs.
  contact:
    name: Kong
    url: 'https://konghq.com'
  x-oas-source: kong/platform-api@73e191354d9b5f5b34b88587927c7e8b4a48a5ff
  x-oas-source-link: 'https://github.com/Kong/platform-api/commit/73e191354d9b5f5b34b88587927c7e8b4a48a5ff'
servers:
  - url: 'https://us.api.konghq.com/v3'
    description: United-States Production region
  - url: 'https://eu.api.konghq.com/v3'
    description: Europe Production region
  - url: 'https://au.api.konghq.com/v3'
    description: Australia Production region
  - url: 'https://me.api.konghq.com/v3'
    description: Middle-East Production region
  - url: 'https://in.api.konghq.com/v3'
    description: India Production region
  - url: 'https://sg.api.konghq.com/v3'
    description: Singapore Production region
paths:
  /audit-log-webhook:
    get:
      operationId: get-audit-logs-webhook
      summary: Get Konnect Audit Log Webhook
      description: Returns configuration for the audit log webhook.
      responses:
        '200':
          $ref: '#/components/responses/AuditLogsWebhook'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Audit Logs
    patch:
      operationId: update-audit-logs-webhook
      summary: Update Konnect Audit Log Webhook
      description: Updates the configuration for a webhook to receive audit logs.
      requestBody:
        $ref: '#/components/requestBodies/UpdateAuditLogsWebhook'
      responses:
        '200':
          $ref: '#/components/responses/AuditLogsWebhook'
        '400':
          $ref: '#/components/responses/AuditLogsWebhookBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Audit Logs
    delete:
      operationId: delete-audit-logs-webhook
      summary: Delete Konnect Audit Log Webhook
      description: 'Removes configuration for the audit log webhook. The destination ID is set to empty, and the webhook enabled field is set to false'
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Audit Logs
  /audit-log-replay-job:
    put:
      operationId: update-audit-log-replay-job
      summary: Update Audit Log Replay Job
      description: Updates a job to re-send audit logs to an organization's webhook.
      requestBody:
        $ref: '#/components/requestBodies/ReplaceAuditLogReplayJob'
      responses:
        '202':
          $ref: '#/components/responses/AuditLogReplayJob'
        '400':
          $ref: '#/components/responses/ReplayJobBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/ReplayJobConflict'
      tags:
        - Audit Logs
    get:
      operationId: get-audit-log-replay-job
      summary: Get Audit Log Replay Job
      description: Returns the audit log replay job's configuration and status.
      responses:
        '200':
          $ref: '#/components/responses/AuditLogReplayJob'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Audit Logs
  /audit-log-destinations:
    get:
      operationId: get-audit-log-destinations
      summary: Get Audit Log Destinations
      description: Returns configuration for the audit log destinations.
      parameters:
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageAfter'
        - $ref: '#/components/parameters/PageBefore'
        - name: filter
          in: query
          description: Filter destinations returned in the response.
          required: false
          schema:
            type: object
            properties:
              name:
                $ref: '#/components/schemas/LegacyStringFieldFilter'
          style: deepObject
      responses:
        '200':
          $ref: '#/components/responses/AuditLogDestinationCollection'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Audit Logs
    post:
      operationId: create-audit-log-destination
      summary: Create Audit Log Destination
      description: Creates a configuration for the audit log destination.
      requestBody:
        $ref: '#/components/requestBodies/CreateAuditLogDestination'
      responses:
        '201':
          $ref: '#/components/responses/AuditLogDestinationSingle'
        '400':
          $ref: '#/components/responses/AuditLogDestinationBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Audit Logs
  '/audit-log-destinations/{auditLogDestinationId}':
    parameters:
      - $ref: '#/components/parameters/AuditLogDestinationId'
    get:
      operationId: get-audit-log-destination
      summary: Get Audit Log Destination
      description: Returns configuration for the audit log destination.
      responses:
        '200':
          $ref: '#/components/responses/AuditLogDestinationSingle'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Audit Logs
    patch:
      operationId: update-audit-log-destination
      summary: Update Audit Log Destination
      description: Updates configuration for the audit log destination.
      requestBody:
        $ref: '#/components/requestBodies/UpdateAuditLogDestination'
      responses:
        '200':
          $ref: '#/components/responses/AuditLogDestinationSingle'
        '400':
          $ref: '#/components/responses/AuditLogDestinationBadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Audit Logs
    delete:
      operationId: delete-audit-log-destination
      summary: Delete Audit Log Destination
      description: Deletes configuration for the audit log destination.
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
      tags:
        - Audit Logs
  /audit-log-webhook/status:
    get:
      operationId: get-audit-logs-webhook-status
      summary: Get Audit Log Webhook Status
      description: Returns status of the audit log webhook.
      responses:
        '200':
          $ref: '#/components/responses/AuditLogsWebhookStatus'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
        - Audit Logs
components:
  parameters:
    AuditLogDestinationId:
      schema:
        type: string
        format: uuid
      name: auditLogDestinationId
      in: path
      required: true
      description: ID of the Audit Log Destination.
    PageAfter:
      name: 'page[after]'
      description: 'Request the next page of data, starting with the item after this parameter.'
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: string
        example: ewogICJpZCI6ICJoZWxsbyB3b3JsZCIKfQ
    PageBefore:
      name: 'page[before]'
      description: 'Request the next page of data, starting with the item before this parameter.'
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: string
        example: ewogICJpZCI6ICJoZWxsbyB3b3JsZCIKfQ
    PageSize:
      name: 'page[size]'
      description: The maximum number of items to include per page. The last page of a collection may include fewer items.
      required: false
      in: query
      allowEmptyValue: true
      schema:
        type: integer
        example: 10
  schemas:
    BaseError:
      description: standard error
      type: object
      properties:
        status:
          description: |
            The HTTP status code of the error. Useful when passing the response
            body to child properties in a frontend UI. Must be returned as an integer.
          type: integer
          readOnly: true
        title:
          description: |
            A short, human-readable summary of the problem. It should not
            change between occurences of a problem, except for localization.
            Should be provided as "Sentence case" for direct use in the UI.
          type: string
          readOnly: true
        type:
          description: The error type.
          type: string
          readOnly: true
        instance:
          description: |
            Used to return the correlation ID back to the user, in the format
            kong:trace:<correlation_id>. This helps us find the relevant logs
            when a customer reports an issue.
          type: string
          readOnly: true
        detail:
          description: |
            A human readable explanation specific to this occurence of the problem.
            This field may contain request/entity data to help the user understand
            what went wrong. Enclose variable values in square brackets. Should be
            provided as "Sentence case" for direct use in the UI.
          type: string
          readOnly: true
      required:
        - status
        - title
        - instance
        - detail
      title: Error
    UnauthorizedError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 401
            title:
              example: Unauthorized
            type:
              example: 'https://httpstatuses.com/401'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Invalid credentials
    ForbiddenError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 403
            title:
              example: Forbidden
            type:
              example: 'https://httpstatuses.com/403'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Forbidden
    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 404
            title:
              example: Not Found
            type:
              example: 'https://httpstatuses.com/404'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Not found
    InvalidRules:
      description: invalid parameters rules
      type: string
      enum:
        - required
        - is_array
        - is_base64
        - is_boolean
        - is_date_time
        - is_integer
        - is_null
        - is_number
        - is_object
        - is_string
        - is_uuid
        - is_fqdn
        - is_arn
        - unknown_property
        - missing_reference
        - is_label
        - matches_regex
        - invalid
        - is_supported_network_availability_zone_list
        - is_supported_network_cidr_block
        - is_supported_provider_region
        - type
      nullable: true
      readOnly: true
    InvalidParameterStandard:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
    InvalidParameterMinimumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - min_length
            - min_digits
            - min_lowercase
            - min_uppercase
            - min_symbols
            - min_items
            - min
          nullable: false
          readOnly: true
        minimum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must have at least 8 characters
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - minimum
    InvalidParameterMaximumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - max_length
            - max_items
            - max
          nullable: false
          readOnly: true
        maximum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must not have more than 8 characters
          readOnly: true
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - maximum
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - enum
          nullable: false
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          items: {}
          minItems: 1
          nullable: false
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
        - field
        - reason
        - rule
        - choices
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
            - dependent_fields
          nullable: true
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          items: {}
          nullable: true
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
        - field
        - rule
        - reason
        - dependents
    InvalidParameters:
      description: invalid parameters
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/InvalidParameterStandard'
          - $ref: '#/components/schemas/InvalidParameterMinimumLength'
          - $ref: '#/components/schemas/InvalidParameterMaximumLength'
          - $ref: '#/components/schemas/InvalidParameterChoiceItem'
          - $ref: '#/components/schemas/InvalidParameterDependentItem'
      minItems: 1
      nullable: false
      uniqueItems: true
    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          required:
            - invalid_parameters
          properties:
            invalid_parameters:
              $ref: '#/components/schemas/InvalidParameters'
    ConflictError:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            status:
              example: 409
            title:
              example: Conflict
            type:
              example: 'https://httpstatuses.com/409'
            instance:
              example: 'kong:trace:1234567890'
            detail:
              example: Conflict
    LegacyStringFieldFilter:
      description: 'Filter using **one** of the following operators: `eq`, `contains`'
      type: object
      properties:
        eq:
          description: The field exactly matches the provided value.
          type: string
          example: '?filter[field_name_here][eq]=foo'
        contains:
          description: The field contains the provided value.
          type: string
          example: '?filter[field_name_here][contains]=foo'
      additionalProperties: false
      x-examples:
        example-1:
          contains: some-value
        example-2:
          eq: some-value
    LogFormat:
      description: The output format of each log messages.
      type: string
      default: cef
      enum:
        - cef
        - json
        - cps
    AuditLogDestination:
      description: Audit Log Destination Schema
      type: object
      properties:
        id:
          description: The unique ID of the audit log destination.
          type: string
          format: uuid
        name:
          description: The name of the audit log destination.
          type: string
        endpoint:
          description: The endpoint that will receive audit log messages.
          type: string
          example: 'https://example.com/audit-logs'
        log_format:
          $ref: '#/components/schemas/LogFormat'
        skip_ssl_verification:
          description: Indicates if the SSL certificate verification of the host endpoint should be skipped when delivering payloads.
          type: boolean
          example: false
          default: false
        created_at:
          description: Timestamp when this webhook was created.
          type: string
          format: date-time
          readOnly: true
        updated_at:
          description: 'Timestamp when this webhook was last updated. Initial value is 0001-01-01T00:00:0Z.'
          type: string
          format: date-time
          readOnly: true
      title: AuditLogDestination
    CursorMetaPage:
      type: object
      properties:
        first:
          description: URI to the first page
          type: string
          format: path
        last:
          description: URI to the last page
          type: string
          format: path
        next:
          description: URI to the next page
          type: string
          format: path
          nullable: true
        previous:
          description: URI to the previous page
          type: string
          format: path
          nullable: true
        size:
          description: Requested page size
          type: number
          example: 10
      required:
        - size
        - next
        - previous
    ListAuditLogDestinations:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AuditLogDestination'
        meta:
          $ref: '#/components/schemas/CursorMetaPage'
      required:
        - data
        - meta
  examples:
    Get-Audit-Logs-Webhook:
      value:
        audit_log_destination_id: 6945c4c4-3e06-4c5c-87e0-726d0cda4e05
        enabled: true
    Get-Audit-Logs-Webhook-Status:
      value:
        webhook_enabled: true
        webhook_status: inactive
        last_attempt_at: '2023-03-21T09:29:14.52Z'
        last_response_code: 401
        last_response_message: Unauthorized
    400-request-format-is-invalid:
      value:
        status: 400
        title: Bad Request
        detail: Could not parse request body
        instance: 'konnect:trace:3674017986744198214'
        invalid_parameters:
          - field: body
            reason: request format is invalid
    400-authorization-cannot-be-blank:
      value:
        status: 400
        title: Bad Request
        detail: Required field missing
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: authorization
            reason: cannot be blank
    400-destination-id-format-is-invalid:
      value:
        status: 400
        title: Bad Request
        detail: Could not parse destination id
        instance: 'konnect:trace:3674017986744198214'
        invalid_parameters:
          - field: audit_log_destination_id
            reason: destination id format is invalid
    Update-Audit-Logs-Webhook:
      value:
        audit_log_destination_id: 6945c4c4-3e06-4c5c-87e0-726d0cda4e05
    Disable-Audit-Logs-Webhook:
      value:
        enabled: false
    Create-Audit-Logs-Webhook:
      value:
        audit_log_destination_id: 6945c4c4-3e06-4c5c-87e0-726d0cda4e05
        enabled: true
    UnauthorizedExample:
      value:
        status: 401
        title: Unauthorized
        instance: 'kong:trace:8347343766220159418'
        detail: Unauthorized
    ForbiddenExample:
      value:
        status: 403
        title: Forbidden
        instance: 'kong:trace:2723154947768991354'
        detail: You do not have permission to perform this action
    NotFoundExample:
      value:
        status: 404
        title: Not Found
        instance: 'kong:trace:6816496025408232265'
        detail: Not Found
    409-job-running:
      value:
        status: 409
        title: Resource Conflict
        instance: 'konnect:trace:6644808935508571943'
        detail: A replay job is currently running
    Audit-Log-Destinations:
      value:
        data:
          - id: 07ec3858-066b-4629-bdc5-d4aa893b424d
            name: Destination-1
            endpoint: 'https://example.com/audit-log'
            log_format: cef
            skip_ssl_verification: false
            created_at: '2023-03-20T09:29:14.52Z'
            updated_at: '2023-03-21T09:29:14.52Z'
          - id: e4374fdc-1f15-4da9-b2e8-7f13d822efe8
            name: Destination-2
            endpoint: 'https://example.com/audit-log'
            log_format: json
            skip_ssl_verification: false
            created_at: '2023-03-20T09:29:14.52Z'
            updated_at: '2023-03-21T09:29:14.52Z'
        meta:
          next: /api/v2/audit-log-destinations?page%5Bafter%5D=f11CXlAMGEVFB0AEQw19QhNYMV5CCkFYSltZUFgPSBJHFwwWFg%3D%3D&page%5Bsize%5=1
          previous: /api/v2/audit-log-destinations?page%5Bbefore%5D=dl8UWVYPEUZFA0sHQw19EUVYMV5BDhcISl1WWVgNQRBBS1gSFw%3D%3D&page%5Bsize%5D=1
          size: 10
    Create-Audit-Log-Destination:
      value:
        id: 07ec3858-066b-4629-bdc5-d4aa893b424d
        name: My Destination
        endpoint: 'https://example.com/audit-log'
        authorization: Bearer token
        log_format: cef
        skip_ssl_verification: false
    Audit-Log-Destination:
      value:
        id: 07ec3858-066b-4629-bdc5-d4aa893b424d
        name: My Destination
        endpoint: 'https://example.com/audit-log'
        log_format: cef
        skip_ssl_verification: false
        created_at: '2023-03-20T09:29:14.52Z'
        updated_at: '2023-03-21T09:29:14.52Z'
    400-endpoint-cannot-be-blank:
      value:
        status: 400
        title: Bad Request
        detail: Required field missing
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: endpoint
            reason: cannot be blank
    400-endpoint-must-be-valid-url:
      value:
        status: 400
        title: Bad Request
        detail: Invalid endpoint
        instance: 'konnect:trace:6644808935508571943'
        invalid_parameters:
          - field: endpoint
            reason: must be a valid URL
    Update-Audit-Log-Destination:
      value:
        endpoint: 'https://example.com/audit-log-json'
        log_format: json
        skip_ssl_verification: false
  requestBodies:
    UpdateAuditLogsWebhook:
      description: The request schema to modify an audit log webhook.
      content:
        application/json:
          schema:
            type: object
            properties:
              audit_log_destination_id:
                description: UUID of an existing audit log destination
                type: string
                format: uuid
              enabled:
                description: Indicates if the data should be sent to the webhook.
                type: boolean
                default: false
          examples:
            Update Audit Log Webhook:
              $ref: '#/components/examples/Update-Audit-Logs-Webhook'
            Disable Audit Log Webhook:
              $ref: '#/components/examples/Disable-Audit-Logs-Webhook'
            Create Audit Log Webhook:
              $ref: '#/components/examples/Create-Audit-Logs-Webhook'
    ReplaceAuditLogReplayJob:
      description: The request schema to replace an audit log replay job.
      content:
        application/json:
          schema:
            type: object
            properties:
              start_at:
                description: |-
                  The start of a date-time range in RFC3339 format e.g. 2017-07-21T17:32:28Z.
                  Must be within the last 7 days.
                type: string
                format: date-time
              end_at:
                description: |-
                  The end of a date-time range in RFC3339 format e.g. 2017-07-21T17:32:28Z.
                  Must be within the last 7 days.
                type: string
                format: date-time
            required:
              - start_at
              - end_at
    CreateAuditLogDestination:
      description: The request schema to create an audit log destination.
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                description: The name of the audit log destination.
                type: string
                example: My Destination
              endpoint:
                description: The endpoint that will receive audit log messages.
                type: string
                example: 'https://example.com/audit-logs'
              authorization:
                description: The value to include in the `Authorization` header when sending audit logs to the webhook.
                type: string
                example: Bearer sometoken
                writeOnly: true
              log_format:
                $ref: '#/components/schemas/LogFormat'
              skip_ssl_verification:
                description: |-
                  Indicates if the SSL certificate verification of the host endpoint should be skipped when delivering payloads.
                  We strongly recommend not setting this to 'true' as you are subject to man-in-the-middle and other attacks.
                  This option should be considered only for self-signed SSL certificates used in a non-production environment.
                type: boolean
                example: false
                default: false
            required:
              - name
              - endpoint
              - log_format
          examples:
            Create Audit Log Destination:
              $ref: '#/components/examples/Create-Audit-Log-Destination'
    UpdateAuditLogDestination:
      description: The request schema to modify an audit log destination.
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                description: The name of the audit log destination.
                type: string
                example: My Destination
              endpoint:
                description: The endpoint that will receive audit log messages.
                type: string
                example: 'https://example.com/audit-logs'
              authorization:
                description: The value to include in the `Authorization` header when sending audit logs to the webhook.
                type: string
                example: Bearer sometoken
                writeOnly: true
              log_format:
                $ref: '#/components/schemas/LogFormat'
              skip_ssl_verification:
                description: |-
                  Indicates if the SSL certificate verification of the host endpoint should be skipped when delivering payloads.
                  We strongly recommend not setting this to 'true' as you are subject to man-in-the-middle and other attacks.
                  This option should be considered only for self-signed SSL certificates used in a non-production environment.
                type: boolean
                example: false
                default: false
          examples:
            Update Audit Log Destination:
              $ref: '#/components/examples/Update-Audit-Log-Destination'
  responses:
    AuditLogsWebhook:
      description: Get response for audit logs webhook
      content:
        application/json:
          schema:
            type: object
            properties:
              audit_log_destination_id:
                description: UUID of an existing audit log destination.
                type: string
                format: uuid
              enabled:
                description: Indicates whether audit data should be sent to the webhook.
                type: boolean
            required:
              - audit_log_destination_id
              - enabled
          examples:
            Get Audit Log Webhook:
              $ref: '#/components/examples/Get-Audit-Logs-Webhook'
    AuditLogsWebhookBadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
          examples:
            Request Format is Invalid:
              $ref: '#/components/examples/400-request-format-is-invalid'
            Authorization Cannot be Blank:
              $ref: '#/components/examples/400-authorization-cannot-be-blank'
            Destination ID format is invalid:
              $ref: '#/components/examples/400-destination-id-format-is-invalid'
    AuditLogsWebhookStatus:
      description: Get response for audit logs webhook status
      content:
        application/json:
          schema:
            type: object
            properties:
              webhook_status:
                description: |-
                  Current status of a webhook. `active` indicates the webhook is sending or ready to send requests.
                  `inactive` indicates the webhook has been turned off due to failed attempts.
                type: string
                example: active
                enum:
                  - active
                  - inactive
              webhook_enabled:
                description: |-
                  Configured status of a webhook. `enabled` indicates the client will accept requests.
                  `disabled` indicates the client will not accept requests.
                type: boolean
                example: true
              last_attempt_at:
                description: 'The last time a request was made to the webhook, regardless of outcome.'
                type: string
                format: date-time
                example: '2023-03-21T09:29:14.52Z'
              last_response_code:
                description: The last response code received from the webhook.
                type: integer
                example: 401
              last_response_message:
                description: The last message received from the webhook. Useful for debugging.
                type: string
                example: Unauthenticated
          examples:
            Get Audit Log Webhook Status:
              $ref: '#/components/examples/Get-Audit-Logs-Webhook-Status'
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/ForbiddenExample'
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
          examples:
            NotFoundExample:
              $ref: '#/components/examples/NotFoundExample'
    AuditLogReplayJob:
      description: Response from fetching or updating an audit log replay job
      content:
        application/json:
          schema:
            type: object
            properties:
              start_at:
                description: 'The start of a date-time range. Initial value is 0001-01-01T00:00:0Z.'
                type: string
                format: date-time
                example: '2017-07-21T17:32:28Z'
              end_at:
                description: 'The end of a date-time range. Initial value is 0001-01-01T00:00:0Z.'
                type: string
                format: date-time
                example: '2017-07-21T17:32:28Z'
              status:
                type: string
                enum:
                  - unconfigured
                  - accepted
                  - pending
                  - running
                  - completed
                  - failed
                readOnly: true
              updated_at:
                description: 'Timestamp when this job was last updated. Initial value is 0001-01-01T00:00:0Z.'
                type: string
                format: date-time
                readOnly: true
    ReplayJobBadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
    ReplayJobConflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConflictError'
          examples:
            Job Running:
              $ref: '#/components/examples/409-job-running'
    AuditLogDestinationCollection:
      description: Response for audit log destinations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListAuditLogDestinations'
          examples:
            Audit Log Destination Collection:
              $ref: '#/components/examples/Audit-Log-Destinations'
    AuditLogDestinationSingle:
      description: Audit log destination response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuditLogDestination'
          examples:
            Audit Log Destination:
              $ref: '#/components/examples/Audit-Log-Destination'
    AuditLogDestinationBadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
          examples:
            Request Format is Invalid:
              $ref: '#/components/examples/400-request-format-is-invalid'
            Authorization Cannot be Blank:
              $ref: '#/components/examples/400-authorization-cannot-be-blank'
            Endpoint Cannot be Blank:
              $ref: '#/components/examples/400-endpoint-cannot-be-blank'
            Endpoint Must be a valid URL:
              $ref: '#/components/examples/400-endpoint-must-be-valid-url'
    Conflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ConflictError'
  securitySchemes:
    personalAccessToken:
      type: http
      scheme: bearer
      bearerFormat: Token
      description: |
        The personal access token is meant to be used as an alternative to basic-auth when accessing Konnect via APIs.
        You can generate a Personal Access Token (PAT) from the [personal access token page](https://cloud.konghq.com/global/account/tokens/) in the Konnect dashboard.
        The PAT token must be passed in the header of a request, for example:
        `curl -X GET 'https://global.api.konghq.com/v2/users/' --header 'Authorization: Bearer kpat_xgfT...'`
    systemAccountAccessToken:
      type: http
      scheme: bearer
      bearerFormat: Token
      description: |
        The system account access token is meant for automations and integrations that are not directly associated with a human identity.
        You can generate a system account Access Token by creating a system account and then obtaining a system account access token for that account.
        The access token must be passed in the header of a request, for example:
        `curl -X GET 'https://global.api.konghq.com/v2/users/' --header 'Authorization: Bearer spat_i2Ej...'`
tags:
  - name: Audit Logs
security:
  - personalAccessToken: []
  - systemAccountAccessToken: []
